// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  boardId: __t.u64().primaryKey().name("board_id"),
  roomId: __t.u64().name("room_id"),
  playerId: __t.identity().name("player_id"),
  boardState: __t.string().name("board_state"),
  updatedAt: __t.timestamp().name("updated_at"),
  moveCount: __t.i32().name("move_count"),
  isCompleted: __t.bool().name("is_completed"),
});
