// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  roomId: __t.u64().primaryKey().name("room_id"),
  roomCode: __t.string().name("room_code"),
  maxPlayers: __t.i32().name("max_players"),
  currentPlayers: __t.i32().name("current_players"),
  isActive: __t.bool().name("is_active"),
  startTime: __t.timestamp().name("start_time"),
  tileOrder: __t.array(__t.u16()).name("tile_order"),
});
