// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export const GameBoard = __t.object("GameBoard", {
  boardId: __t.u64(),
  roomId: __t.u64(),
  playerId: __t.identity(),
  boardState: __t.string(),
  updatedAt: __t.timestamp(),
  isCompleted: __t.bool(),
});
export type GameBoard = __Infer<typeof GameBoard>;

export const GameTimer = __t.object("GameTimer", {
  timerId: __t.u64(),
  schedule: __t.scheduleAt(),
});
export type GameTimer = __Infer<typeof GameTimer>;

export const Player = __t.object("Player", {
  playerId: __t.u64(),
  roomId: __t.u64(),
  userId: __t.identity(),
  playerName: __t.string(),
  endTime: __t.timestamp(),
  isReady: __t.bool(),
});
export type Player = __Infer<typeof Player>;

export const Room = __t.object("Room", {
  roomId: __t.u64(),
  roomCode: __t.string(),
  maxPlayers: __t.i32(),
  currentPlayers: __t.i32(),
  isActive: __t.bool(),
  startTime: __t.timestamp(),
  tileOrder: __t.array(__t.u16()),
});
export type Room = __Infer<typeof Room>;

export const Timer = __t.object("Timer", {
  timerId: __t.u64(),
  roomId: __t.u64(),
  timerType: __t.string(),
  data: __t.string(),
  scheduledAt: __t.scheduleAt(),
});
export type Timer = __Infer<typeof Timer>;

