// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import { type Infer as __Infer } from "spacetimedb";

// Import all reducer arg schemas
import CreateRoomReducer from "../create_room_reducer";
import JoinRoomReducer from "../join_room_reducer";
import LeaveRoomReducer from "../leave_room_reducer";
import MarkPuzzleCompletedReducer from "../mark_puzzle_completed_reducer";
import SetPlayerReadyReducer from "../set_player_ready_reducer";
import StartGameCountdownReducer from "../start_game_countdown_reducer";
import UpdateGameBoardReducer from "../update_game_board_reducer";

export type CreateRoomParams = __Infer<typeof CreateRoomReducer>;
export type JoinRoomParams = __Infer<typeof JoinRoomReducer>;
export type LeaveRoomParams = __Infer<typeof LeaveRoomReducer>;
export type MarkPuzzleCompletedParams = __Infer<typeof MarkPuzzleCompletedReducer>;
export type SetPlayerReadyParams = __Infer<typeof SetPlayerReadyReducer>;
export type StartGameCountdownParams = __Infer<typeof StartGameCountdownReducer>;
export type UpdateGameBoardParams = __Infer<typeof UpdateGameBoardReducer>;

